### PR TITLE
Create self-contained Demo Application

### PR DESCRIPTION
**Pull request by danielemaddaluno**
Pull request for #4

### CODE REVIEW

**Comment by eckig** [comment]
Thanks for putting this together, I'll look into it!

**Comment by eckig** [comment]
- The build process now requires a specific JDK (Liberica Full JDK) - not sure if I like this?
- Switching to Liberica fails the tests, which now requires running without Monocle, not sure how the headless tests are running, but they seem to work?

And finally the build fails with:
```
Bundler Windows Application Image skipped because of a configuration problem: The configured main jar does not exist graph-editor-demo-11.0.5.jar in the input directory 
Advice to fix: The main jar must be specified relative to the input directory (not an absolute path), and must exist within that directory
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:804)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:751)
    at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:313)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:64)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
    at org.codehaus.classworlds.Launcher.main (Launcher.java:47)

```

**Comment by eckig** [comment]
In summary, integrating this would mean running two github actions:

1. The one currently active for testing and building the JARs
2. And we need to create a separate one using Liberica, skipping the tests but building the native images?

**Comment by danielemaddaluno** [comment]
You are right, with the last commit I decommented the `maven-jar-plugin` but including this plugin it does not create the jar correctly.
I thought that it could coexist with `maven-dependency-plugin`.
I'll comment it again so at least you can test the app app generation. Then you can decide how to proceed.

However I used `Liberica Full JDK` because it was easier for me to use a distro which already has `openJFX` inside, probably `OpenJDK`+`OpenJFX` (or `Oracle JDK` + `JavaFX`) would work but I have not tested with that.

**Comment by eckig** [comment]
Nice work! Works like a charm (at least on windows).

Now this got me thinking: Do we really need a specific JDK (that is bundled with JavaFX), because JavaFX is already present (loaded via maven dependencies)? Do you think we can make this work?

**Comment by danielemaddaluno** [comment]
This is what I understood:
- when we used to create a self-contained application with Java <= 8 the `jpackager` used to create a runtime that included the full jre indiscriminately (without distinguishing which parts of the jre the application really uses).
- the principle of `module-info.java` in Java > 8 projects is to filter from the jre just the really useful parts of the jre, in order to create a light version of the jre (which included only what is specified in the `module-info.java`) when packaging a self-contained application.
- so I think (but I'm not really sure, a part of me hope that I'm wrong) that the problem with those scripts (that I run with `Liberica full jdk`) is not linked to the jar dependencies of JavaFX (which as you said are included by maven) but it's linked to which parts of the jre is needed to run JavaFX itself that have to be put inside the "light jre". And these parts must be ready to be copied from the distribution (if are missing the self-contained application will not work).
- Not every jdk distribution already includes fx mods and binaries because Oracle removed them from the main release from java > 8, opening the project [openjfx](https://openjfx.io/), and generally you have to install javafx separately inside your jdk.
- If possible I would try launching it with OpenJDK (checking if there is a full distribution). I have never used github actions, but I can make some tests if you guide me.

**Comment by eckig** [comment]
I am willing to put together the github actions.

But I have an idea, let me try something..

**Comment by eckig** [comment]
This batch file actually works with AdoptOpenJDK (without any bundled JavaFX):

```
set JAVA_VERSION=14
set MAIN_JAR=graph-editor-demo-%PROJECT_VERSION%.jar

set INSTALLER_TYPE=app-image

IF EXIST target\installer rmdir /S /Q target\installer

xcopy /S /Q target\libs\* target\installer\input\libs\
copy target\%MAIN_JAR% target\installer\input\libs\

call "%JAVA_HOME%\bin\jpackage" ^
      --type %INSTALLER_TYPE% ^
      --dest target/installer ^
      --main-class de.tesis.dynaware.grapheditor.demo.GraphEditorDemo ^
      --main-jar %MAIN_JAR% ^
      --name GraphEditorDemo ^
      --input target/installer/input/libs ^
      --java-options -Xmx512m 
```

But: The `.exe` file does not launch and does not print any clues as to why.
I checked the lib folder and it looks complete... Do you have any idea?

**Comment by eckig** [comment]
>     * the principle of `module-info.java` in Java > 8 projects is to filter from the jre just the really useful parts of the jre, in order to create a light version of the jre (which included only what is specified in the `module-info.java`) when packaging a self-contained application with `jdeps + jlink + jpackage`.

Not really, the `module-info.java` is meant as a module descriptor for the Java Module System (JPMS).

>     * so I think (but I'm not really sure, a part of me hope that I'm wrong) that the problem with those scripts (that I run with `Liberica full jdk`) is not linked to the jar dependencies of JavaFX (which as you said are included by maven) but it's linked to which parts of the jre is needed to run JavaFX itself that have to be put inside the "light jre". And these parts must be ready to be copied from the distribution (if they are missing the self-contained application will not work).

As far as I have understood: The problem is that the jpackager has two modes of operation: One for applications built with the JPMS and one without. The graph editor is a JPMS application but not all of its depencies: For example the Eclipse EMF dependencies do not have a `module-info.java` and is refused by the packager.

That is why we are treating the graph editor demo as a non-JPMS application which leads to some isses.. at least, that is my guess.

**Comment by danielemaddaluno** [comment]
> But: The `.exe` file does not launch and does not print any clues as to why.
> Do you have any idea?

No ideas but when you run the exe, if it does not launch I think there should be a ".log" file generated in the same folder.
Maybe there you can find some other infos about the reason it does not launch.

On mac when I launch the script with `AdoptOpenJDK 15` as it is it gives me`Error: Module javafx.controls not found` while creating the runtime-image.

**Comment by eckig** [comment]
> I know `module-info.java` is for `Java Module System`, but I'm pretty sure it's the base to infer which parts of JRE are useful to be imported in the self-contained app. I think it's used by `jdeps` to automatically detect required modules.

That's right. That is also why the jdeps call does not list all of the dependencies: If you point the jdeps call to the demo Jar file, it will find all depedencies.

Fyi: There is no log file...

**Comment by danielemaddaluno** [comment]
> Fyi: There is no log file...
🤔 I see... 😞 
I have you already tried to launch the exe by command line?

**Comment by eckig** [comment]
> I have you already tried to launch the exe by command line?
Yep, did nothing. Just exits immediately with no printouts...

I will have another look at this this weekend.

**Comment by eckig** [comment]
At the current state the JDK packing tools do not work with non-module depedencies.

Now we could go and make the demo module a non-module (by removing the module-info) and then just create a plain fat-jar with a main-class.

The other option would be to wait for [JEP392](https://openjdk.java.net/jeps/392) (scheduled for JDK 16).

**Comment by eckig** [comment]
I just discovered a maven plugin that supposedly automates the process of creating an executable: https://github.com/fvarrui/JavaPackager

I need some time to look into this...

**Comment by danielemaddaluno** [comment]
Super cool! Can't wait to hear about it!

**Pull request closed without merging**
